Repository zextras/carbonio-files-ce, pull requests merged in 2024-09, with the labels that each got.

#125 chore(release): 0.13.1
  CHANGELOG.md
  boot/pom.xml
  core/pom.xml
  package/PKGBUILD
  pom.xml
Labels: release

#126 ci: fix support ubuntu noble for RC
  Jenkinsfile
Labels: bug, ci

#127 ci: fix check snapshot bot removing 'request changes' event
  Jenkinsfile
Labels: ci
